// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package test1

import (
	"demo/api/test1"
)

type ControllerV1 struct{}

func NewV1() test1.ITest1V1 {
	return &ControllerV1{}
}
